server:
  port : 8088
spring:
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: rental
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/store
  sql:
    init:
      mode: always
  jmx:
    server:




